### ISSUE TITLE
Add option to set NTP server address

### ISSUE THREAD

**Issue by danielkucera** [lora-gateway/esxp1302#21]
Using the Chinese one is not optimal for the rest of the world :)

**Comment by dennis4lora** [comment]
Good proposal. providing option to set NTP server is also necessary for the gateway used in an isolated internal network. 

I propose just add this option in the web UI. It should be easy. 

> Using the Chinese one is not optimal...

At first I wanted to use the global NTP server address, but it didn't work well in China, so I chose the Chinese one. Time to improve it now. :laughing: 



**BTW**: I think the web UI design is a little ugly even without adding this NTP server option. Let me open a new issue to discuss it.

**Comment by dennis4lora** [comment]
I've added this option but keep `cn.pool.ntp.org` as the default value. I think this can remind users to just change **cn** to their own country code.

BTW: In fact it works with `pool.ntp.org` on my test but very slow, not sure if it behaves the same on other regions.
