### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by DanielCao0** [lora-gateway/esxp1302#5]
Compiling .pio\build\esp32dev\main\loragw_debug.o
main/http_server.c:28:10: fatal error: webpage.h: No such file or directory

*****************************************************************
* Looking for webpage.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:webpage.h"
* Web  > https://registry.platformio.org/search?q=header:webpage.h
*
*****************************************************************

 #include "webpage.h"
          ^~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32dev\main\http_server.o] Error 1

**Comment by danielkucera** [comment]
did you make some changes?
It works for me with latest main branch.

**Comment by dennis4lora** [comment]
@DanielCao0 :
This error happens because the file **webpage.h** is dumped from file **main/webpage.html** by script **scripts/dump_html.py** happens in step `./run_me.sh make`. Since the PlatformIO way skips this step, this error shows.

The **temporal solution** is just run `./run_me.sh make` first and ignore the errors, then back to the PlatformIO way.

Still, a rightly solution is needed. 😄 

BTW: the format of **webpage.h** is not as I expected, also needs to be fixed...

**Comment by dennis4lora** [comment]
Should be fixed now in the **main** branch with below 2 commits:
- [update scripts to Python3](# 40f01e6)
- [keep dumped head files](# 02a41e7)

Please check. Thanks for reporting this.

**Comment by DanielCao0** [comment]
Problem solved, thank you very much

**Comment by DanielCao0** [comment]
Linking .pio\build\esp32dev\firmware.elf
c:/users/daniel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\esp-idf\freertos\libfreertos.a(port_common.o):(.literal.main_task+0x1c): undefined reference to `app_main'
c:/users/daniel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\esp-idf\freertos\libfreertos.a(port_common.o): in function `main_task':
C:\Users\daniel\.platformio\packages\framework-espidf\components\freertos\port/port_common.c:135: undefined reference to `app_main'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1
================================================================================================================ [FAILED] Took 269.64 seconds ================================================================================================================
 *  The terminal process "C:\Users\daniel\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by dennis4lora** [comment]
I never compiled it under Windows. However, I have a guess about the reason of this error.

In fact, **main/main.c** is a soft link to **main/lora_pkt_fwd.c** under Linux. Under Windows, maybe this link is broken. If so, then just rename **main/lora_pkt_fwd.c** to **main/main.c** should fix it.

**Comment by dennis4lora** [comment]
I just cloned the code in Windows, and found both link files (**sdkconfig.esp32dev** and **main/main.c**) become normal files whose contents are the linked file names (or empty files if download the code as a zip file), which cause problem.

@DanielCao0 How did you deal with file **sdkconfig.esp32dev**? Do you just copied **sdkconfig**?

One potential solution is using hard link instead, which I guess should work on both Linux and Windows; but I need to check first.

**Comment by DanielCao0** [comment]
Processing esp32dev (platform: espressif32@5.4.0; framework: espidf; board: esp32dev)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.4.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf @ 3.40405.230623 (4.4.5)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.40400.0 (4.4.0)
 - tool-idf @ 1.0.1
 - tool-mconf @ 1.4060000.20190628 (406.0.0)
 - tool-ninja @ 1.9.0
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\esp32dev\main\main.o
Compiling .pio\build\esp32dev\main\base64.o
main/main.c:1:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before '.' token
 lora_pkt_fwd.c
             ^
Compiling .pio\build\esp32dev\main\ioe.o
Compiling .pio\build\esp32dev\main\http_server.o
Compiling .pio\build\esp32dev\main\jitqueue.o
Compiling .pio\build\esp32dev\main\loragw_aux.o
Compiling .pio\build\esp32dev\main\loragw_cal.o
Compiling .pio\build\esp32dev\main\loragw_debug.o
*** [.pio\build\esp32dev\main\main.o] Error 1
============================================================================= [FAILED] Took 21.08 seconds =============================================================================

 *  The terminal process "C:\Users\daniel\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by DanielCao0** [comment]
This is what I just cloned and compiled using vscode+platform+windows ....

**Comment by DanielCao0** [comment]
[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32@5.4.0
framework = espidf
board = esp32dev
monitor_speed = 115200

**Comment by dennis4lora** [comment]
Can you just rename or copy **main/lora_pkt_fwd.c** to **main/main.c** and compile again?

**Comment by DanielCao0** [comment]
esptool.py v4.4
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Linking .pio\build\esp32dev\firmware.elf
c:/users/daniel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\main\main.o:(.literal.esp_print_tasks+0x10): undefined reference to `vTaskList'
c:/users/daniel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\main\main.o: in function 
`esp_print_tasks':
E:\esp32_gateway\esxp1302/main/main.c:1316: undefined reference to `vTaskList'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1
============================================================================= [FAILED] Took 265.19 seconds =============================================================================
 *  The terminal process "C:\Users\daniel\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by dennis4lora** [comment]
I just add a commit: [change soft link to hard link to support Windows PlatformIO compile](https://github.com/lora-gateway/esxp1302/commit/ccdfde4b6cb3da2fe38fd6fd8d2d5f01fa5738e5); now the build step works all right in my Windows.

Can you pull it and try again?

**Comment by DanielCao0** [comment]
Thank you. 

esptool.py v4.4
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Linking .pio\build\esp32dev\firmware.elf
Retrieving maximum program size .pio\build\esp32dev\firmware.elf
Checking size .pio\build\esp32dev\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  47.9% (used 156904 bytes from 327680 bytes)
Flash: [========= ]  89.5% (used 938229 bytes from 1048576 bytes)
Building .pio\build\esp32dev\firmware.bin
esptool.py v4.4
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.

**Comment by lora-gateway** [comment]
Thanks @danielkucera for providing a better solution (https://github.com/lora-gateway/esxp1302/commit/1ee2ffe5b9c325d68ae35936873ddad9786d5f56) than the hard link way. 
And I'm sure this issue can be closed. 😃
